<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * An immutable snapshot of a form's JSON schema.
 *
 * This table is the heart of the design, and it exists for three reasons:
 *
 * 1. THE BRIEF REQUIRES A SINGLE SOURCE OF TRUTH. The `schema` column is it.
 *    The canvas, the raw JSON editor, the public renderer and the server-side
 *    validator all read this one column. There is no second, normalised
 *    `form_fields` table that could drift out of sync with it.
 *
 * 2. SUBMISSIONS MUST STAY READABLE. If someone fills in a form on Monday and
 *    the owner deletes a field on Tuesday, Monday's answers still have to
 *    render with their original labels. Every submission stores the
 *    `form_version_id` it was filled against, so we can always reconstruct the
 *    exact form the respondent saw.
 *
 * 3. VERSIONING AND ROLLBACK COME FREE. Because rows are append-only, "restore
 *    v3" is just repointing `forms.current_version_id`. No destructive edit,
 *    no data loss, and a complete audit trail of who changed what and when.
 *
 * Rows are never UPDATEd. Every save that actually changes the schema writes a
 * new row with the next version_number.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('form_versions', function (Blueprint $table) {
            $table->id();

            $table->foreignId('form_id')->constrained()->cascadeOnDelete();

            // Monotonic per form, starting at 1. Displayed to the user as "v3".
            $table->unsignedInteger('version_number');

            // THE SOURCE OF TRUTH: sections, fields, per-field config and
            // validation rules. Validated against a JSON Schema document
            // before it is ever written here.
            $table->json('schema');

            // SHA-256 of the canonicalised schema. Lets a save be a no-op when
            // nothing actually changed, so autosave and the raw-editor's
            // two-way sync do not spawn a new version on every keystroke.
            $table->char('checksum', 64);

            // Where this version came from. Useful in the UI ("generated by
            // AI", "imported from resume-form.docx") and for analytics.
            $table->enum('origin', ['manual', 'ai_create', 'ai_edit', 'import', 'rollback'])
                ->default('manual');

            // Free-text changelog entry, e.g. "made phone required".
            $table->string('note', 255)->nullable();

            // Nullable so a version survives the deletion of the user account
            // that created it.
            $table->foreignId('created_by')->nullable()
                ->constrained('users')->nullOnDelete();

            $table->timestamps();

            // Enforces the monotonic sequence and powers "fetch v3 of form 12".
            $table->unique(['form_id', 'version_number'], 'form_versions_sequence_uq');

            // The version-history sidebar: newest first for one form.
            $table->index(['form_id', 'created_at'], 'form_versions_history_idx');
        });

        // Now that the target table exists, wire up the pointer from `forms`.
        // nullOnDelete rather than cascade: losing a version should never
        // silently delete the whole form.
        Schema::table('forms', function (Blueprint $table) {
            $table->foreign('current_version_id')
                ->references('id')->on('form_versions')
                ->nullOnDelete();
        });
    }

    public function down(): void
    {
        Schema::table('forms', function (Blueprint $table) {
            $table->dropForeign(['current_version_id']);
        });

        Schema::dropIfExists('form_versions');
    }
};
